[workspace]
members = ["crates/poincare-lib", "crates/poincare-app"]
resolver = "3"

[workspace.dependencies]
poincare-lib = { path = "crates/poincare-lib" }
viewport-lib = "0.14.0"
wgpu = { version = "27.0", features = ["metal", "vulkan"] }
glam = { version = "=0.30.10", features = ["bytemuck"] }
bytemuck = { version = "1.25", features = ["derive"] }
