[package]
name = "poincare-notebook-app"
version = "0.1.0"
edition = "2024"
description = "Notebook application for Poincare documents"
license = "MIT"
repository = "https://github.com/grimandgreedy/poincare"
homepage = "https://github.com/grimandgreedy/poincare"
documentation = "https://docs.rs/poincare-notebook-app"
keywords = ["math", "notebook", "egui"]
categories = ["mathematics", "science", "gui"]

[[bin]]
name = "poincare-notebook"
path = "src/main.rs"

[dependencies]
poincare-evaluator = { workspace = true }
poincare-evaluator-poincare = { workspace = true }
poincare-lib = { workspace = true }
poincare-notebook-lib = { workspace = true }
viewport-lib = { workspace = true }
glam = { workspace = true }
eframe = { version = "=0.33.3", default-features = false, features = ["wgpu", "default_fonts", "persistence", "x11", "wayland"] }
egui = { version = "=0.33.3" }
grimdock = { version = "0.2.0" }
rfd = "0.15"
serde_json = "1"
